import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

export const TRANSLATIONS = {
  en: {
    brand_title: "NER SENTINEL AI",
    sub_title: "Problem Statement 26002",
    nav_dashboard: "Command Dashboard",
    nav_convoys: "Convoy Telematics (AIS-140)",
    nav_routes: "Route Intelligence",
    nav_simulation: "Hazard Simulation Studio",
    nav_field_report: "Field Incident Report",
    online_satellite: "🟢 Live Satellite (Online)",
    offline_mode: "🟡 Offline Field Mode (Local Graph)",
    sign_in: "Officer Sign In / Register",
    logout: "Sign Out",
    fastest_route: "Fastest Speed Route",
    safest_route: "Safest Disaster-Resilient Route",
    analyze_corridors: "Analyze Strategic Corridors",
    trigger_reroute: "⚡ Trigger Dynamic A* Reroute",
    total_convoys: "Total Active Fleets",
    pol_tankers: "POL Fuel Tankers",
    medical_aid: "Critical Medical Aid",
    food_grains: "FCI Food Grains",
    delayed_convoys: "Rerouting / Delayed",
    landslide_alert: "Landslide Risk Warning",
    flood_alert: "Flash Flood Choke Point",
    rockfall_alert: "High-Altitude Rockfall Hazard",
    heavy_rain: "Heavy Monsoon Inundation",
    status_in_transit: "IN TRANSIT",
    status_delayed: "DELAYED LANDSLIDE",
    status_rerouting: "REROUTING",
    status_delivered: "DELIVERED",
    priority_critical: "CRITICAL HIGH",
    priority_high: "HIGH",
    priority_medium: "MEDIUM",
    origin_point: "Origin (Starting Point)",
    dest_point: "Destination (Target Point)",
    transit_time: "Est. Transit Time",
    distance: "Distance",
    risk_score: "Disaster Risk Score",
    refueling_bases: "Verified PSU Fuel Stations",
    isro_verified: "🛰️ ISRO Bhuvan Synced",
    submit_incident: "Submit Field Report to HQ",
    report_desc: "Describe road conditions, mud accumulation, or structural damage..."
  },
  as: {
    brand_title: "এন ই আৰ চেন্টিনেল এআই",
    sub_title: "সমস্যা বিবৃতি ২৬০০২",
    nav_dashboard: "মুখ্য নিয়ন্ত্ৰণ ডেশ্ববৰ্ড",
    nav_convoys: "কনভয় টেলিমেটিক্স (AIS-140)",
    nav_routes: "পথ বুদ্ধিমত্তা ও পৰিকল্পনা",
    nav_simulation: "বিপদ অনুৰূপণ ষ্টুডিঅ'",
    nav_field_report: "ক্ষেত্ৰৰ ঘটনা প্ৰতিবেদন",
    online_satellite: "🟢 লাইভ উপগ্ৰহ সংযোগ (অনলাইন)",
    offline_mode: "🟡 অফলাইন ফিল্ড মোড (স্থানীয় গ্ৰাফ)",
    sign_in: "বিষয়া / নাগৰিক প্ৰৱেশ",
    logout: "প্ৰস্থান",
    fastest_route: "দ্ৰুততম গতিৰ পথ",
    safest_route: "নিৰাপদ দুৰ্যোগ-প্ৰতিৰোধী পথ",
    analyze_corridors: "কৰিডৰ বিশ্লেষণ কৰক",
    trigger_reroute: "⚡ গতিশীল নতুন পথ নিৰ্ধাৰণ কৰক",
    total_convoys: "মুঠ সক্ৰিয় কনভয়",
    pol_tankers: "ইন্ধন টেংকাৰ (POL)",
    medical_aid: "জৰুৰীকালীন চিকিৎসা যোগান",
    food_grains: "খাদ্য শস্য (FCI)",
    delayed_convoys: "বিলম্বিত / নতুন পথত",
    landslide_alert: "ভূমিস্খলনৰ সতৰ্কতা",
    flood_alert: "হঠাত্ বানপানীৰ সতৰ্কতা",
    rockfall_alert: "শিলা খহি পৰাৰ আশংকা",
    heavy_rain: "প্ৰবল বাৰিষাৰ বৰষুণ",
    status_in_transit: "যাত্ৰাত আছে",
    status_delayed: "ভূমিস্খলনত বিলম্ব",
    status_rerouting: "নতুন পথত গতিশীল",
    status_delivered: "বিতৰণ সম্পূৰ্ণ",
    priority_critical: "অতি জৰুৰী",
    priority_high: "উচ্চ অগ্ৰাধিকাৰ",
    priority_medium: "মধ্যম",
    origin_point: "উৎস স্থান (যাত্ৰা আৰম্ভ)",
    dest_point: "গন্তব্য স্থান (লক্ষ্য)",
    transit_time: "আনুমানিক সময়",
    distance: "দূৰত্ব",
    risk_score: "দুৰ্যোগৰ বিপদাশংকা",
    refueling_bases: "প্ৰমাণিত পেট্ৰল পাম্প",
    isro_verified: "🛰️ ইছৰো ভূৱন প্ৰমাণিত",
    submit_incident: "মুখ্য কাৰ্যালয়লৈ প্ৰতিবেদন প্ৰেৰণ",
    report_desc: "পথৰ অৱস্থা, বোকা বা ক্ষতিৰ বিৱৰণ দিয়ক..."
  },
  bn: {
    brand_title: "এন ই আর সেন্টিনেল এআই",
    sub_title: "সমস্যা বিবৃতি ২৬০০২",
    nav_dashboard: "কমান্ড ড্যাশবোর্ড",
    nav_convoys: "কনভয় টেলিমেটিক্স (AIS-140)",
    nav_routes: "রুট ইন্টেলিজেন্স ও পরিকল্পনা",
    nav_simulation: "দুর্যোগ সিমুলেশন স্টুডিও",
    nav_field_report: "মাঠ পর্যায়ের প্রতিবেদন",
    online_satellite: "🟢 লাইভ স্যাটেলাইট (অনলাইন)",
    offline_mode: "🟡 অফলাইন ফিল্ড মোড (লোকাল গ্রাফ)",
    sign_in: "অফিসার / নাগরিক লগইন",
    logout: "লগআউট",
    fastest_route: "দ্রুততম গতির রুট",
    safest_route: "নিরাপদ দুর্যোগ-সহনশীল রুট",
    analyze_corridors: "হাইওয়ে করিডোর বিশ্লেষণ",
    trigger_reroute: "⚡ ডায়নামিক রি-রুট গণনা করুন",
    total_convoys: "মোট সক্রিয় কনভয়",
    pol_tankers: "জ্বালানি ট্যাংকার (POL)",
    medical_aid: "জরুরি চিকিৎসা সরঞ্জাম",
    food_grains: "খাদ্য শস্য (FCI)",
    delayed_convoys: "ভূমিধসে বিলম্বিত / নতুন রুটে",
    landslide_alert: "ভূমিধসের চরম সতর্কতা",
    flood_alert: "আকস্মিক বন্যা বাধা",
    rockfall_alert: "পাহাড়ে পাথর পতনের ঝুঁকি",
    heavy_rain: "প্রবল বর্ষণ ও জলাবদ্ধতা",
    status_in_transit: "চলমান",
    status_delayed: "ভূমিধসে বিলম্বিত",
    status_rerouting: "নতুন রুটে ধাবমান",
    status_delivered: "পৌঁছে গেছে",
    priority_critical: "জরুরি উচ্চ",
    priority_high: "উচ্চ অগ্রাধিকার",
    priority_medium: "মাঝারি",
    origin_point: "যাত্রার শুরু (উৎপত্তি)",
    dest_point: "গন্তব্যস্থল",
    transit_time: "আনুমানিক সময়",
    distance: "দূরত্ব",
    risk_score: "দুর্যোগ ঝুঁকি স্কোর",
    refueling_bases: "অনুমোদিত জ্বালানি স্টেশন",
    isro_verified: "🛰️ ইসরো ভুবন ভেরিফায়েড",
    submit_incident: "হেডকোয়ার্টারে রিপোর্ট পাঠান",
    report_desc: "রাস্তার ক্ষয়ক্ষতি বা কাদার বিবরণ দিন..."
  },
  hi: {
    brand_title: "एनईआर सेंटिनल एआई",
    sub_title: "समस्या विवरण 26002",
    nav_dashboard: "कमांड डैशबोर्ड",
    nav_convoys: "कॉनवॉय टेलीमैटिक्स (AIS-140)",
    nav_routes: "मार्ग बुद्धिमत्ता एवं विश्लेषण",
    nav_simulation: "आपदा सिमुलेशन स्टूडियो",
    nav_field_report: "क्षेत्रीय घटना रिपोर्ट",
    online_satellite: "🟢 लाइव सैटेलाइट (ऑनलाइन)",
    offline_mode: "🟡 ऑफ़लाइन फील्ड मोड (लोकल ग्राफ)",
    sign_in: "अधिकारी / नागरिक लॉगिन",
    logout: "लॉगआउट",
    fastest_route: "तीव्रतम गति मार्ग",
    safest_route: "सुरक्षित आपदा-प्रतिरोधी मार्ग",
    analyze_corridors: "हाईवे कॉरिडोर का विश्लेषण करें",
    trigger_reroute: "⚡ डायनामिक नया मार्ग तय करें",
    total_convoys: "कुल सक्रिय राहत काफिले",
    pol_tankers: "ईंधन टैंकर (POL)",
    medical_aid: "आपातकालीन चिकित्सा सहायता",
    food_grains: "खाद्यान्न आपूर्ति (FCI)",
    delayed_convoys: "भूस्खलन से विलंबित / पुनर्मार्गित",
    landslide_alert: "भूस्खलन की चेतावनी",
    flood_alert: "अचानक बाढ़ का खतरा",
    rockfall_alert: "चट्टान गिरने की चेतावनी",
    heavy_rain: "भारी मानसूनी वर्षा",
    status_in_transit: "मार्ग में अग्रसर",
    status_delayed: "भूस्खलन में विलंबित",
    status_rerouting: "नए मार्ग पर अग्रसर",
    status_delivered: "सुरक्षित पहुँचा",
    priority_critical: "अत्यंत महत्वपूर्ण",
    priority_high: "उच्च प्राथमिकता",
    priority_medium: "मध्यम",
    origin_point: "प्रारंभिक स्थल (उत्पत्ति)",
    dest_point: "गंतव्य स्थल",
    transit_time: "अनुमानित यात्रा समय",
    distance: "कुल दूरी",
    risk_score: "आपदा जोखिम स्तर",
    refueling_bases: "सत्यापित पेट्रोल पंप",
    isro_verified: "🛰️ इसरो भुवन सत्यापित",
    submit_incident: "मुख्यालय को रिपोर्ट भेजें",
    report_desc: "सड़क की स्थिति, मलबे या क्षति का विवरण दें..."
  },
  mni: {
    brand_title: "এন ই আর সেন্তিনেল এআই",
    sub_title: "প্রোব্লেম স্তেতমেন্ত ২৬০০২",
    nav_dashboard: "কমান্দ দেশবোর্দ",
    nav_convoys: "কোনভোয় তেলিমিতিক্স (AIS-140)",
    nav_routes: "লমবীগী লৌশিং অমসুং রুত",
    nav_simulation: "নুংশিৎ ইশিংগী সিমুলেসন",
    nav_field_report: "লমদমগী পাউদম পিবী",
    online_satellite: "🟢 সেতেলাইত শম্নরে (ওনলাইন)",
    offline_mode: "🟡 ওফলাইন মোদ (ইন্তরনেত লৈতবা)",
    sign_in: "ওফিসার / মীচম চংবা",
    logout: "থোকপা",
    fastest_route: "খ্বাইদগী য়াংবা লমবী",
    safest_route: "খ্বাইদগী অশোই-অঙাম লৈতবা লমবী",
    analyze_corridors: "লমবী নৈনবীয়ু",
    trigger_reroute: "⚡ অনৌবা রুত খনবীয়ু",
    total_convoys: "পুম্নমক কোনভোয়",
    pol_tankers: "থাউ তাঙ্কর (POL)",
    medical_aid: "হীদাক-লাংথক তেংবাং",
    food_grains: "চাং-খোং (FCI)",
    delayed_convoys: "চিং লোইথবা / থিংবা",
    landslide_alert: "চিং লোইথবগী চেক্সিনৱা",
    flood_alert: "ইশিং তুম্বগী চেক্সিনৱা",
    rockfall_alert: "নুং খাকপগী চেক্সিনৱা",
    heavy_rain: "অকনবা নোং চুবা",
    status_in_transit: "চৎলিবা",
    status_delayed: "চিং লোইথবনা থিংলে",
    status_rerouting: "অনৌবা রুততা চৎলি",
    status_delivered: "য়ৌরে",
    priority_critical: "খ্বাইদগী মরুওইবা",
    priority_high: "মরুওইবা",
    priority_medium: "ময়াং অমুক",
    origin_point: "হৌরকফম",
    dest_point: "য়ৌগদবা মফম",
    transit_time: "মতুম চংবা",
    distance: "অরাপ্পা",
    risk_score: "অশোইবা লেপ্নবা",
    refueling_bases: "পেত্রোল পম্প",
    isro_verified: "🛰️ ইসরো ভুৱন শম্নরে",
    submit_incident: "হেদকুৱাতরদা পাউ পিবী",
    report_desc: "লমবীগী ফীভম ইবীয়ু..."
  },
  lus: {
    brand_title: "NER SENTINEL AI",
    sub_title: "Problem Statement 26002",
    nav_dashboard: "Command Dashboard",
    nav_convoys: "Convoy Telematics (AIS-140)",
    nav_routes: "Kawng Ruahmanna & Hriatpuina",
    nav_simulation: "Chhiatrupna Simulation Studio",
    nav_field_report: "Hmunhma Chanchin Thawnna",
    online_satellite: "🟢 Live Satellite (Online)",
    offline_mode: "🟡 Offline Field Mode (Internet Tel Lovin)",
    sign_in: "Officer / Mipui Luhluhna",
    logout: "Chhuahna",
    fastest_route: "Kawng Rang Ber",
    safest_route: "Kawng Him Ber",
    analyze_corridors: "Kawng dinhmun endik rawh",
    trigger_reroute: "⚡ Kawng dang zawng rawh",
    total_convoys: "Convoy Zawng Zawng",
    pol_tankers: "Hriak Phur Tanker (POL)",
    medical_aid: "Damdawi Lam Tanpuina",
    food_grains: "Buhfai Supply (FCI)",
    delayed_convoys: "Leimin Vanga Thuanawp",
    landslide_alert: "Leimin hlauhawm hriattirna",
    flood_alert: "Tui lian hlauhawm",
    rockfall_alert: "Lung tla hlauhawm",
    heavy_rain: "Ruahtui tla nasa",
    status_in_transit: "Kawngah Kal Mek",
    status_delayed: "Leimin Vanga Thuanawp",
    status_rerouting: "Kawng Dang Zawh Mek",
    status_delivered: "Thleng Kim Ta",
    priority_critical: "HMANHMAWH THLAK",
    priority_high: "PAWIMAWH",
    priority_medium: "LSAWNG",
    origin_point: "Chhuahna Hmun",
    dest_point: "Thlenna Hmun",
    transit_time: "Hun Duang Chhin",
    distance: "Hlat Zawng",
    risk_score: "Hlauhawm Tehna",
    refueling_bases: "Petrol Pump Hriatpui",
    isro_verified: "🛰️ ISRO Bhuvan Nemngheh",
    submit_incident: "HQ-ah Report Thawn Rawh",
    report_desc: "Kawng chhiat dan leh leimin zual zia ziak rawh..."
  },
  kha: {
    brand_title: "NER SENTINEL AI",
    sub_title: "Problem Statement 26002",
    nav_dashboard: "Ka Dashboard Bahal",
    nav_convoys: "Ka Convoy Telematics (AIS-140)",
    nav_routes: "Ka Jingbatai Lynti",
    nav_simulation: "Ka Simulation Jingjia",
    nav_field_report: "Ka Report Jingjia ha Madan",
    online_satellite: "🟢 Live Satellite (Online)",
    offline_mode: "🟡 Offline Mode (Khlem Internet)",
    sign_in: "Bsut Officer / Nongleiteng",
    logout: "Mih noh",
    fastest_route: "Ka Lynti kaba Sted Tam",
    safest_route: "Ka Lynti kaba Shngain Tam",
    analyze_corridors: "Bishar ia ki Lynti Bah",
    trigger_reroute: "⚡ Wad ia ka Lynti thymmai",
    total_convoys: "Baroh ki Convoy",
    pol_tankers: "Ki Tanker Umphniang (POL)",
    medical_aid: "Ki Dawai & Jingiarap",
    food_grains: "Ki Jingbam (FCI)",
    delayed_convoys: "Ki ba Sahkut ha ka Twad Khndew",
    landslide_alert: "Ka Jingma Twad Khndew",
    flood_alert: "Ka Jingma Shlei Um",
    rockfall_alert: "Ka Jingma Hap Maw",
    heavy_rain: "Jinghap slap jur",
    status_in_transit: "Dang Leit ha Lynti",
    status_delayed: "Sahkut Twad Khndew",
    status_rerouting: "Lynti ba la Pynkylla",
    status_delivered: "Poi Suk",
    priority_critical: "KABA DONKAM EH",
    priority_high: "KABA DONKAM",
    priority_medium: "PDENG",
    origin_point: "Kaba Mih (Nongrim)",
    dest_point: "Kaba Thmu ban Poi",
    transit_time: "Ka Por ba Antad",
    distance: "Ka Jingjngai",
    risk_score: "Ka Jingma",
    refueling_bases: "Ki Petrol Pump ba la pynskhem",
    isro_verified: "🛰️ ISRO Bhuvan la Pynskhem",
    submit_incident: "Phah Report sha Headquarter",
    report_desc: "Batai shaphang ka jingma ha surok..."
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('ner_sentinel_lang') || 'en';
  });

  const changeLanguage = (langCode) => {
    if (TRANSLATIONS[langCode]) {
      setLanguage(langCode);
      localStorage.setItem('ner_sentinel_lang', langCode);
    }
  };

  const t = (key, fallback = '') => {
    const langDict = TRANSLATIONS[language] || TRANSLATIONS.en;
    if (langDict[key]) return langDict[key];
    if (TRANSLATIONS.en[key]) return TRANSLATIONS.en[key];
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
}

export const useLanguage = useTranslation;

export default LanguageContext;
